services:
  socketio:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
    logging:
      driver: json-file
      options:
        max-size: 1m
